package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable
{

    private Long id;
    private String district;
    private String city;
    private String street;
    private String adresstext;

    public Address()
    {
    }

    public Address(String district, String city, String street, String adresstext)
    {
        this.district = district;
        this.city = city;
        this.street = street;
        this.adresstext = adresstext;
    }

    public Long getId()
    {
        return this.id;
    }

    public Address setId(Long id)
    {
        this.id = id;
        return this;
    }

    public String getDistrict()
    {
        return this.district;
    }

    public Address setDistrict(String district)
    {
        this.district = district;
        return this;
    }

    public String getCity()
    {
        return this.city;
    }

    public Address setCity(String city)
    {
        this.city = city;
        return this;
    }

    public String getStreet()
    {
        return this.street;
    }

    public Address setStreet(String street)
    {
        this.street = street;
        return this;
    }

    public String getAdresstext()
    {
        return this.adresstext;
    }

    public Address setAdresstext(String adresstext)
    {
        this.adresstext = adresstext;
        return this;
    }

}
