package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Bill generated by hbm2java
 */
public class Bill implements java.io.Serializable
{

    private Long id;
    private Long restaurantid;
    private String date;
    private String clock;
    private Double amount;
    private String orders;

    public Bill()
    {
    }

    public Bill(Long restaurantid, String date, String clock, Double amount, String orders)
    {
        this.restaurantid = restaurantid;
        this.date = date;
        this.clock = clock;
        this.amount = amount;
        this.orders = orders;
    }

    public Long getId()
    {
        return this.id;
    }

    public Bill setId(Long id)
    {
        this.id = id;
        return this;
    }

    public Long getRestaurantid()
    {
        return this.restaurantid;
    }

    public Bill setRestaurantid(Long restaurantid)
    {
        this.restaurantid = restaurantid;
        return this;
    }

    public String getDate()
    {
        return this.date;
    }

    public Bill setDate(String date)
    {
        this.date = date;
        return this;
    }

    public String getClock()
    {
        return this.clock;
    }

    public Bill setClock(String clock)
    {
        this.clock = clock;
        return this;
    }

    public Double getAmount()
    {
        return this.amount;
    }

    public Bill setAmount(Double amount)
    {
        this.amount = amount;
        return this;
    }

    public String getOrders()
    {
        return this.orders;
    }

    public Bill setOrders(String orders)
    {
        this.orders = orders;
        return this;
    }

}
