package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Complaint generated by hbm2java
 */
public class Complaint implements java.io.Serializable
{

    private Long id;
    private Long restaurantid;
    private String complaintHeader;
    private String complaintBody;
    private long userid;

    public Complaint()
    {
    }

    public Complaint(Long restaurantid, String complaintHeader, String complaintBody, Integer userid)
    {
        this.restaurantid = restaurantid;
        this.complaintHeader = complaintHeader;
        this.complaintBody = complaintBody;
        this.userid = userid;
    }

    public Long getId()
    {
        return this.id;
    }

    public Complaint setId(Long id)
    {
        this.id = id;
        return this;

    }

    public Long getRestaurantid()
    {
        return this.restaurantid;
    }

    public Complaint setRestaurantid(Long restaurantid)
    {
        this.restaurantid = restaurantid;
        return this;

    }

    public String getComplaintHeader()
    {
        return this.complaintHeader;
    }

    public Complaint setComplaintHeader(String complaintHeader)
    {
        this.complaintHeader = complaintHeader;
        return this;

    }

    public String getComplaintBody()
    {
        return this.complaintBody;
    }

    public Complaint setComplaintBody(String complaintBody)
    {
        this.complaintBody = complaintBody;
        return this;

    }

    public long getUserid()
    {
        return this.userid;
    }

    public Complaint setUserid(long userid)
    {
        this.userid = userid;
        return this;
    }

}
