package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Dinnertable generated by hbm2java
 */
public class DinnerTable implements java.io.Serializable
{

    private Long id;
    private Long restaurantid;
    private Integer statu;
    private Integer capacity;
    private String name;

    public DinnerTable()
    {
    }

    public DinnerTable(Long restaurantid, Integer statu, Integer capacity, String name)
    {
        this.restaurantid = restaurantid;
        this.statu = statu;
        this.capacity = capacity;
        this.name = name;
    }

    public Long getId()
    {
        return this.id;
    }

    public DinnerTable setId(Long id)
    {
        this.id = id;
        return this;

    }

    public Long getRestaurantid()
    {
        return this.restaurantid;
    }

    public DinnerTable setRestaurantid(Long restaurantid)
    {
        this.restaurantid = restaurantid;
        return this;

    }

    public Integer getStatu()
    {
        return this.statu;
    }

    public DinnerTable setStatu(Integer statu)
    {
        this.statu = statu;
        return this;

    }

    public Integer getCapacity()
    {
        return this.capacity;
    }

    public DinnerTable setCapacity(Integer capacity)
    {
        this.capacity = capacity;
        return this;

    }

    public String getName()
    {
        return this.name;
    }

    public DinnerTable setName(String name)
    {
        this.name = name;
        return this;
    }

}
