package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable
{

    private Long id;
    private String name;
    private String surname;
    private String tcNo;
    private Long adressid;
    private String phone;
    private String mail;
    private String password;
    private Double score;
    private Integer voteCount;
    private long restaurantid;

    public Employee()
    {
    }

    public Employee(String name, String surname, String tcNo, Long adressid, String phone, String mail, String password, Double score, Integer voteCount, long restaurantid)
    {
        this.name = name;
        this.surname = surname;
        this.tcNo = tcNo;
        this.adressid = adressid;
        this.phone = phone;
        this.mail = mail;
        this.password = password;
        this.score = score;
        this.voteCount = voteCount;
        this.restaurantid = restaurantid;
    }

    public Long getId()
    {
        return this.id;
    }

    public Employee setId(Long id)
    {
        this.id = id;
        return this;

    }

    public String getName()
    {
        return this.name;
    }

    public Employee setName(String name)
    {
        this.name = name;
        return this;

    }

    public String getSurname()
    {
        return this.surname;
    }

    public Employee setSurname(String surname)
    {
        this.surname = surname;
        return this;

    }

    public String getTcNo()
    {
        return this.tcNo;
    }

    public Employee setTcNo(String tcNo)
    {
        this.tcNo = tcNo;
        return this;

    }

    public Long getAdressid()
    {
        return this.adressid;
    }

    public Employee setAdressid(Long adressid)
    {
        this.adressid = adressid;
        return this;

    }

    public String getPhone()
    {
        return this.phone;
    }

    public Employee setPhone(String phone)
    {
        this.phone = phone;
        return this;

    }

    public String getMail()
    {
        return this.mail;
    }

    public Employee setMail(String mail)
    {
        this.mail = mail;
        return this;

    }

    public String getPassword()
    {
        return this.password;
    }

    public Employee setPassword(String password)
    {
        this.password = password;
        return this;

    }

    public Double getScore()
    {
        return this.score;
    }

    public Employee setScore(Double score)
    {
        this.score = score;
        return this;

    }

    public Integer getVoteCount()
    {
        return this.voteCount;
    }

    public Employee setVoteCount(Integer voteCount)
    {
        this.voteCount = voteCount;
        return this;

    }

    public long getRestaurantid()
    {
        return this.restaurantid;
    }

    public Employee setRestaurantid(long restaurantid)
    {
        this.restaurantid = restaurantid;
        return this;
    }

}
