package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable
{

    private Long id;
    private Long restaurantid;
    private Long urunid;
    private Integer piece;
    private long masaid;
    private String statu;
    private String date;
    private String clock;

    public Order()
    {
    }

    public Order(Long restaurantid, Long urunid, Integer piece, long masaid, String statu, String date, String clock)
    {
        this.restaurantid = restaurantid;
        this.urunid = urunid;
        this.piece = piece;
        this.masaid = masaid;
        this.statu = statu;
        this.date = date;
        this.clock = clock;
    }

    public Long getId()
    {
        return this.id;
    }

    public Order setId(Long id)
    {
        this.id = id;
        return this;

    }

    public Long getRestaurantid()
    {
        return this.restaurantid;
    }

    public Order setRestaurantid(Long restaurantid)
    {
        this.restaurantid = restaurantid;
        return this;

    }

    public Long getUrunid()
    {
        return this.urunid;
    }

    public Order setUrunid(Long urunid)
    {
        this.urunid = urunid;
        return this;

    }

    public Integer getPiece()
    {
        return this.piece;
    }

    public Order setPiece(Integer piece)
    {
        this.piece = piece;
        return this;

    }

    public long getMasaid()
    {
        return this.masaid;
    }

    public Order setMasaid(long masaid)
    {
        this.masaid = masaid;
        return this;

    }

    public String getStatu()
    {
        return this.statu;
    }

    public Order setStatu(String statu)
    {
        this.statu = statu;
        return this;

    }

    public String getDate()
    {
        return this.date;
    }

    public Order setDate(String date)
    {
        this.date = date;
        return this;

    }

    public String getClock()
    {
        return this.clock;
    }

    public Order setClock(String clock)
    {
        this.clock = clock;
        return this;
    }

}
