package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable
{

    private Long id;
    private long restaurantid;
    private String name;
    private Long stock;
    private Double price;
    private String definiton;
    private long categoryid;
    private Double score;
    private Integer voteCount;

    public Product()
    {
    }

    public Product(long restaurantid, String name, long categoryid)
    {
        this.restaurantid = restaurantid;
        this.name = name;
        this.categoryid = categoryid;
    }

    public Product(long restaurantid, String name, Long stock, Double price, String definiton, long categoryid, Double score, Integer voteCount)
    {
        this.restaurantid = restaurantid;
        this.name = name;
        this.stock = stock;
        this.price = price;
        this.definiton = definiton;
        this.categoryid = categoryid;
        this.score = score;
        this.voteCount = voteCount;
    }

    public Long getId()
    {
        return this.id;
    }

    public Product setId(Long id)
    {
        this.id = id;
        return this;

    }

    public long getRestaurantid()
    {
        return this.restaurantid;
    }

    public Product setRestaurantid(long restaurantid)
    {
        this.restaurantid = restaurantid;
        return this;

    }

    public String getName()
    {
        return this.name;
    }

    public Product setName(String name)
    {
        this.name = name;
        return this;

    }

    public Long getStock()
    {
        return this.stock;
    }

    public Product setStock(Long stock)
    {
        this.stock = stock;
        return this;

    }

    public Double getPrice()
    {
        return this.price;
    }

    public Product setPrice(Double price)
    {
        this.price = price;
        return this;

    }

    public String getDefiniton()
    {
        return this.definiton;
    }

    public Product setDefiniton(String definiton)
    {
        this.definiton = definiton;
        return this;

    }

    public long getCategoryid()
    {
        return this.categoryid;
    }

    public Product setCategoryid(long categoryid)
    {
        this.categoryid = categoryid;
        return this;

    }

    public Double getScore()
    {
        return this.score;
    }

    public Product setScore(Double score)
    {
        this.score = score;
        return this;

    }

    public Integer getVoteCount()
    {
        return this.voteCount;
    }

    public Product setVoteCount(Integer voteCount)
    {
        this.voteCount = voteCount;
        return this;
    }

}
