package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Productimages generated by hbm2java
 */
public class ProductImages implements java.io.Serializable
{

    private Long id;
    private String imagestring;
    private long productid;

    public ProductImages()
    {
    }

    public ProductImages(String imagestring, long productid)
    {
        this.imagestring = imagestring;
        this.productid = productid;
    }

    public Long getId()
    {
        return this.id;
    }

    public ProductImages setId(Long id)
    {
        this.id = id;
        return this;

    }

    public String getImagestring()
    {
        return this.imagestring;
    }

    public ProductImages setImagestring(String imagestring)
    {
        this.imagestring = imagestring;
        return this;

    }

    public long getProductid()
    {
        return this.productid;
    }

    public ProductImages setProductid(long productid)
    {
        this.productid = productid;
        return this;
    }

}
