package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Request generated by hbm2java
 */
public class Request implements java.io.Serializable
{

    private Long id;
    private long dinnertableid;
    private long userid;
    private long restaurantid;
    private Long garsonid;

    public Request()
    {
    }

    public Request(long dinnertableid, long userid, long restaurantid)
    {
        this.dinnertableid = dinnertableid;
        this.userid = userid;
        this.restaurantid = restaurantid;
    }

    public Request(long dinnertableid, long userid, long restaurantid, Long garsonid)
    {
        this.dinnertableid = dinnertableid;
        this.userid = userid;
        this.restaurantid = restaurantid;
        this.garsonid = garsonid;
    }

    public Long getId()
    {
        return this.id;
    }

    public Request setId(Long id)
    {
        this.id = id;
        return this;

    }

    public long getDinnertableid()
    {
        return this.dinnertableid;
    }

    public Request setDinnertableid(long dinnertableid)
    {
        this.dinnertableid = dinnertableid;
        return this;

    }

    public long getUserid()
    {
        return this.userid;
    }

    public Request setUserid(long userid)
    {
        this.userid = userid;
        return this;

    }

    public long getRestaurantid()
    {
        return this.restaurantid;
    }

    public Request setRestaurantid(long restaurantid)
    {
        this.restaurantid = restaurantid;
        return this;

    }

    public Long getGarsonid()
    {
        return this.garsonid;
    }

    public Request setGarsonid(Long garsonid)
    {
        this.garsonid = garsonid;
        return this;
    }

}
