package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable
{

    private Long id;
    private long restaurantid;
    private String date;
    private String clock;
    private Long userid;
    private String username;
    private String usersurname;
    private long dinnertableid;

    public Reservation()
    {
    }

    public Reservation(long restaurantid, String date, String clock, String username, String usersurname, long dinnertableid)
    {
        this.restaurantid = restaurantid;
        this.date = date;
        this.clock = clock;
        this.username = username;
        this.usersurname = usersurname;
        this.dinnertableid = dinnertableid;
    }

    public Reservation(long restaurantid, String date, String clock, Long userid, String username, String usersurname, long dinnertableid)
    {
        this.restaurantid = restaurantid;
        this.date = date;
        this.clock = clock;
        this.userid = userid;
        this.username = username;
        this.usersurname = usersurname;
        this.dinnertableid = dinnertableid;
    }

    public Long getId()
    {
        return this.id;
    }

    public Reservation setId(Long id)
    {
        this.id = id;
        return this;

    }

    public long getRestaurantid()
    {
        return this.restaurantid;
    }

    public Reservation setRestaurantid(long restaurantid)
    {
        this.restaurantid = restaurantid;
        return this;

    }

    public String getDate()
    {
        return this.date;
    }

    public Reservation setDate(String date)
    {
        this.date = date;
        return this;

    }

    public String getClock()
    {
        return this.clock;
    }

    public Reservation setClock(String clock)
    {
        this.clock = clock;
        return this;

    }

    public Long getUserid()
    {
        return this.userid;
    }

    public Reservation setUserid(Long userid)
    {
        this.userid = userid;
        return this;

    }

    public String getUsername()
    {
        return this.username;
    }

    public Reservation setUsername(String username)
    {
        this.username = username;
        return this;

    }

    public String getUsersurname()
    {
        return this.usersurname;
    }

    public Reservation setUsersurname(String usersurname)
    {
        this.usersurname = usersurname;
        return this;

    }

    public long getDinnertableid()
    {
        return this.dinnertableid;
    }

    public Reservation setDinnertableid(long dinnertableid)
    {
        this.dinnertableid = dinnertableid;
        return this;
    }

}
