package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Restaurantcomments generated by hbm2java
 */
public class RestaurantComments implements java.io.Serializable
{

    private Long id;
    private String date;
    private String clock;
    private long userid;
    private long restaurantid;
    private String comment;

    public RestaurantComments()
    {
    }

    public RestaurantComments(String date, String clock, long userid, long restaurantid, String comment)
    {
        this.date = date;
        this.clock = clock;
        this.userid = userid;
        this.restaurantid = restaurantid;
        this.comment = comment;
    }

    public Long getId()
    {
        return this.id;
    }

    public RestaurantComments setId(Long id)
    {
        this.id = id;
        return this;

    }

    public String getDate()
    {
        return this.date;
    }

    public RestaurantComments setDate(String date)
    {
        this.date = date;
        return this;

    }

    public String getClock()
    {
        return this.clock;
    }

    public RestaurantComments setClock(String clock)
    {
        this.clock = clock;
        return this;

    }

    public long getUserid()
    {
        return this.userid;
    }

    public RestaurantComments setUserid(long userid)
    {
        this.userid = userid;
        return this;

    }

    public long getRestaurantid()
    {
        return this.restaurantid;
    }

    public RestaurantComments setRestaurantid(long restaurantid)
    {
        this.restaurantid = restaurantid;
        return this;

    }

    public String getComment()
    {
        return this.comment;
    }

    public RestaurantComments setComment(String comment)
    {
        this.comment = comment;
        return this;
    }

}
