package com.garson.model.entity;
// Generated Dec 7, 2016 1:03:25 AM by Hibernate Tools 4.3.1

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant implements java.io.Serializable
{

    private Long id;
    private String name;
    private String definition;
    private Double serviceScore;
    private Integer voteCount;

    public Restaurant()
    {
    }

    public Restaurant(String name)
    {
        this.name = name;
    }

    public Restaurant(String name, String definition, Double serviceScore, Integer voteCount)
    {
        this.name = name;
        this.definition = definition;
        this.serviceScore = serviceScore;
        this.voteCount = voteCount;
    }

    public Long getId()
    {
        return this.id;
    }

    public Restaurant setId(Long id)
    {
        this.id = id;
        return this;

    }

    public String getName()
    {
        return this.name;
    }

    public Restaurant setName(String name)
    {
        this.name = name;
        return this;

    }

    public String getDefinition()
    {
        return this.definition;
    }

    public Restaurant setDefinition(String definition)
    {
        this.definition = definition;
        return this;

    }

    public Double getServiceScore()
    {
        return this.serviceScore;
    }

    public Restaurant setServiceScore(Double serviceScore)
    {
        this.serviceScore = serviceScore;
        return this;

    }

    public Integer getVoteCount()
    {
        return this.voteCount;
    }

    public Restaurant setVoteCount(Integer voteCount)
    {
        this.voteCount = voteCount;
        return this;
    }

}
